### ISSUE TITLE
Exception while invoking method collection/update?

### ISSUE THREAD

**Issue by Ajaxsoap** [nicolaslopezj/roles#12]
Hi @nicolaslopezj,

After updating the roles to version 2.0.3 last night,I get this error on the console when i tried to update any collection.

```
Exception while invoking method '/products/update' TypeError: Object function (a) {                                                     // 2   // 10
I20151130-04:38:40.607(8)?   return this.filter(function(i) {                                                       // 3   // 11
I20151130-04:38:40.607(8)?     return a.indexOf(i) < 0;                                                             // 4   // 12
I20151130-04:38:40.607(8)?   });                                                                                    // 5   // 13
I20151130-04:38:40.607(8)? } has no method 'indexOf'
I20151130-04:38:40.607(8)?     at packages/nicolaslopezj_roles/helpers.js:7:1
I20151130-04:38:40.607(8)?     at Array.forEach (native)
I20151130-04:38:40.607(8)?     at Function._.each._.forEach (packages/underscore/packages/underscore.js:134:1)
I20151130-04:38:40.607(8)?     at willChangeWithParent (packages/nicolaslopezj_roles/helpers.js:6:1)
I20151130-04:38:40.607(8)?     at deny.update (packages/nicolaslopezj_roles/roles.js:363:1)
I20151130-04:38:40.607(8)?     at packages/mongo/collection.js:1068:1
I20151130-04:38:40.607(8)?     at Array.some (native)
I20151130-04:38:40.608(8)?     at Function._.some._.any (packages/underscore/packages/underscore.js:262:1)
I20151130-04:38:40.608(8)?     at [object Object].Mongo.Collection._validatedUpdate (packages/mongo/collection.js:1066:1)
I20151130-04:38:40.608(8)?     at [object Object].m.(anonymous function) (packages/mongo/collection.js:892:1)

```

How do i downgrade the version before the upgrade? I forgot the version number before the upgrade.

Thanks,

**Comment by Ajaxsoap** [comment]
I got managed to downgrade to 2.0.2 on versions folder inside .meteor. Everything works fine now.
